-- Submission time is generated by PostgreSQL and cannot be chosen by applicants.
-- Earlier timestamps receive priority only when the matching algorithm needs a tie-breaker.
create index if not exists survey_responses_submitted_at_idx
  on public.survey_responses (submitted_at, id);

comment on column public.survey_responses.submitted_at is
'Server-generated submission time. Use ascending order for first-submitted tie-break priority.';
